name: deploy.yml
on: 'push'

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  push-to-registry:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_REPO: ${{ vars.DOCKERHUB_REPO }}
    needs: code-quality
    steps:
      - uses: actions/checkout@v5

      - name: Build and Push to Docker Hub
        uses: ./.github/actions/build-and-push

  deploy:
    runs-on: ubuntu-latest
    needs: push-to-registry
    steps:
      - name: Deploy to Render
        run: curl "${{ secrets.RENDER_WEBHOOK_URL }}&imgURL=docker.io%2F${{ vars.DOCKERHUB_REPO }}%3Alatest"
