name: deploy.yml
on: 'push'

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml

  push-to-registry:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - uses: actions/checkout@v5

      - name: Build and Push to Docker Hub
        uses: ./.github/actions/build-and-push
        with:
          dockerhub_username: ${{ vars.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub_repo: ${{ vars.DOCKERHUB_REPO }}

  deploy:
    runs-on: ubuntu-latest
    needs: push-to-registry
    steps:
      - name: Deploy to Render
        run: curl "${{ secrets.RENDER_WEBHOOK_URL }}&imgURL=docker.io%2F${{ vars.DOCKERHUB_REPO }}%3Alatest"
